### ISSUE TITLE
Not working due to problems described in the log

### ISSUE THREAD

**Issue by kanedatatsaki** [MrBartusek/MeteoalarmCard#40]
### Log entries

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/meteoalarm/binary_sensor.py", line 88, in update
    alert = self._api.get_alert()
  File "/usr/local/lib/python3.8/site-packages/meteoalertapi/meteoalertapi.py", line 34, in get_alert
    feed_data = xmltodict.parse(text)
  File "/usr/local/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 28, column 71

**Comment by MrBartusek** [comment]
Hey, this issue is related to metroalarm integration, not the card. Please report it here https://github.com/home-assistant/core/issues
